// Read-only presentation. Financial and operational rules remain in the existing domain/services.
import {active,cancelled,finished,balance,monthly,status,today,sum,n,find} from './domain.mjs';
import {worksFor} from './work-model.mjs';
const paths={
 home:'m3 10 9-7 9 7M5 9v11h5v-6h4v6h5V9',orders:'M7 3h10v18H5V3h2m1 0v4h8V3M8 11h8M8 15h5',
 clients:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m17-6a4 4 0 0 1 3 4v2M13 3a4 4 0 0 1 0 8M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8',
 vehicles:'m4 10 2-6h12l2 6M3 10h18v8H3zm2 8v3m14-3v3M6 14h2m8 0h2',production:'m14 6 4-4 4 4-4 4m-4-4L4 16l4 4L18 10M3 3l5 2 2 5-5-2z',
 employees:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 21v-2a8 8 0 0 1 16 0v2M9 16l3 3 3-3',
 payments:'M3 5h18v14H3zM3 9h18M6 15h4',inventory:'m3 7 9-4 9 4-9 4zm0 0v10l9 4 9-4V7m-9 4v10M7 5l10 4',
 expenses:'M6 3h12v18l-3-2-3 2-3-2-3 2zM9 7h6m-6 4h6m-6 4h3',monthly:'M4 20V10m6 10V4m6 16v-8m5 8H2',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',
 history:'M3 11a9 9 0 1 1 2 7M3 4v7h7m2-4v6l4 2',finance:'M12 2v20m5-16H9a3 3 0 0 0 0 6h6a3 3 0 0 1 0 6H6',
 search:'m20 20-5-5M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14',calendar:'M5 5h14v16H5zM8 2v6m8-6v6M5 11h14m-10 4h2m2 0h2',
 plus:'M12 4v16M4 12h16',arrow:'M4 12h16m-6-6 6 6-6 6',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',
 more:'M4 6h16M4 12h16M4 18h16',check:'m5 12 4 4L19 6',chevron:'m9 5 7 7-7 7',user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8M4 21a8 8 0 0 1 16 0'
};
export const icon=name=>'<svg class="ui-icon" aria-hidden="true" focusable="false" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+(paths[name]||paths.orders)+'"/></svg>';
export const navigation=[['home','Inicio'],['orders','Órdenes'],['clients','Clientes'],['vehicles','Vehículos'],['production','Producción'],['employees','Empleados'],['payments','Pagos'],['inventory','Inventario'],['expenses','Gastos'],['monthly','Reportes'],['history','Historial'],['finance','Finanzas'],['settings','Configuración']];
export function processProgress(d,o){
 const works=worksFor(d,o.id),standard=['Desabolladura','Preparación','Pintura','Brillado'];
 return [...standard,...new Set(works.map(w=>w.process).filter(p=>!standard.includes(p)))].map(name=>{
  const group=works.filter(w=>w.process===name),total=sum(group,w=>n(w.quantity)),done=sum(group.filter(w=>w.status==='Terminado'),w=>n(w.quantity));
  return {name,total,done,running:group.some(w=>w.status==='En proceso')};
 });
}
export function createDashboard({d,esc,money,date,button,empty,vehicleText,client}){
 const orders=d.orders.filter(active),production=orders.filter(o=>!finished(d,o)),attention=orders.filter(o=>finished(d,o)),month=monthly(d,today().slice(0,7));
 const tile=(name,label,value,href,link,tone)=>'<a class="metric dashboard-metric '+tone+'" data-metric="'+name+'" href="#'+href+'"><span class="metric-icon">'+icon(name)+'</span><div><span>'+label+'</span><strong>'+value+'</strong><span class="metric-link">'+link+' '+icon('arrow')+'</span></div></a>';
 const steps=o=>'<ol class="process-track" aria-label="Progreso de procesos">'+processProgress(d,o).filter(p=>['Desabolladura','Preparación','Pintura','Brillado'].includes(p.name)).map(p=>'<li class="'+(p.total&&p.done===p.total?'complete':p.running?'running':'')+'"><span class="step-dot">'+(p.total&&p.done===p.total?icon('check'):'')+'</span><span>'+esc(p.name)+'</span><small>'+(p.total?p.done+'/'+p.total:'—')+'</small></li>').join('')+'<li class="'+(finished(d,o)?'complete':'')+'"><span class="step-dot">'+(finished(d,o)?icon('check'):'')+'</span><span>Terminado</span><small>'+(finished(d,o)?'Listo':'Pendiente')+'</small></li></ol>';
 const recent=o=>'<article class="recent-order"><a class="order-preview" href="#order/'+o.id+'"><span class="vehicle-emblem">'+icon('vehicles')+'</span><div><strong>'+esc(o.number)+'</strong><span>'+esc(vehicleText(o))+'</span></div><span class="badge">'+esc(status(d,o))+'</span></a><div class="order-facts"><span>'+icon('calendar')+esc(date(o.entryDate))+' <span aria-hidden="true">→</span> '+esc(o.dueDate?date(o.dueDate):'Sin fecha')+'</span><span>'+icon('user')+esc(client(o).name)+'</span><span>'+icon('finance')+money(o.total)+'</span><span>Pendiente: <strong>'+money(balance(d,o))+'</strong></span></div>'+steps(o)+'</article>';
 const productionCard=o=>'<article class="production-preview"><a href="#order/'+o.id+'" class="order-preview"><span class="vehicle-emblem">'+icon('vehicles')+'</span><div><strong>'+esc(vehicleText(o))+'</strong><span>'+esc(o.number)+'</span></div><span class="status-dot" title="'+esc(status(d,o))+'"></span></a><div class="process-bars">'+processProgress(d,o).map((p,i)=>'<div class="process-bar tone-'+i%4+'"><span>'+esc(p.name)+'</span><small>'+(p.total?p.done+'/'+p.total:'Sin trabajos')+'</small><progress value="'+p.done+'" max="'+(p.total||1)+'" aria-label="'+esc(p.name+': '+p.done+' de '+p.total+' piezas terminadas')+'"></progress></div>').join('')+'</div></article>';
 const quick=(label,sub,name,action,tone)=>button('<span class="quick-icon">'+icon(name)+'</span><span><strong>'+label+'</strong><small>'+sub+'</small></span>',action,'','quick-action '+tone).replace('<button','<button aria-label="'+label+'"');
 return '<section class="dashboard-metrics" aria-label="Resumen del taller">'+tile('orders','Órdenes activas',orders.length,'orders','Ver todas','tone-gold')+tile('vehicles','En producción',production.length,'production','Ver producción','tone-blue')+tile('finance','Por cobrar',money(sum(d.orders.filter(o=>!cancelled(o)&&o.status!=='Cotización'),o=>balance(d,o))),'payments','Ver pagos','tone-green')+tile('monthly','Ingresos del mes',money(month.cash),'monthly','Ver reportes','tone-violet')+'</section><div class="dashboard-columns"><section class="dashboard-panel"><div class="section-title"><h2>Órdenes recientes</h2><a href="#orders">Ver todas '+icon('arrow')+'</a></div>'+(orders.slice().sort((a,b)=>Number(b.id)-Number(a.id)).slice(0,2).map(recent).join('')||empty('Tu próxima orden empieza aquí.'))+'</section><section class="dashboard-panel"><div class="section-title"><h2>Producción hoy</h2><a href="#production">Ver producción '+icon('arrow')+'</a></div>'+(production.slice(0,2).map(productionCard).join('')||empty('No hay trabajos en producción.'))+'</section></div><section class="quick-actions" aria-label="Accesos rápidos">'+quick('Nueva orden','Registrar vehículo','plus','order-new','tone-blue')+quick('Nuevo cliente','Agregar cliente','clients','client-new','tone-green')+quick('Registrar pago','Abono o saldo','finance','quick-pay','tone-violet')+quick('Nuevo gasto','Materiales u otros','expenses','quick-cost','tone-orange')+quick('Agregar inventario','Registrar material','inventory','product-new','tone-slate')+'</section>'+(attention.length?'<section class="dashboard-panel attention-panel"><div class="section-title"><h2>Necesitan atención</h2><span>'+attention.length+' terminados por entregar</span></div>'+attention.map(o=>'<div class="attention-row"><a href="#order/'+o.id+'">'+esc(o.number)+' · '+esc(vehicleText(o))+'</a>'+button(balance(d,o)>0?'Cobrar saldo':'Revisar entrega',balance(d,o)>0?'pay':'open-order',o.id,'compact')+'</div>').join('')+'</section>':'');
}
export function searchResults(d,term){
 const normalize=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),q=normalize(term).trim();if(!q)return [];
 const match=values=>normalize(values.join(' ')).includes(q);
 return [...d.orders.filter(o=>!o.deleted&&!o.deletedAt).filter(o=>{const v=find(d,'vehicles',o.vehicleId)||{},c=find(d,'clients',o.clientId)||{};return match([o.number,v.brand,v.model,v.plate,c.name,c.phone]);}).map(o=>({href:'order/'+o.id,title:o.number,detail:[find(d,'vehicles',o.vehicleId)?.brand,find(d,'vehicles',o.vehicleId)?.model,status(d,o)].filter(Boolean).join(' · '),icon:'orders'})),...d.clients.filter(c=>match([c.name,c.phone])).map(c=>({href:'client/'+c.id,title:c.name,detail:c.phone||'Cliente',icon:'clients'})),...d.vehicles.filter(v=>match([v.brand,v.model,v.plate])).map(v=>({href:'client/'+v.clientId,title:[v.brand,v.model].join(' '),detail:v.plate||'Vehículo',icon:'vehicles'}))].slice(0,8);
}
