export const DOCUMENT_CSS=`
.customer-document{font:13px/1.4 Arial,Helvetica,sans-serif;color:#20252b;background:#fff;max-width:816px;width:100%;margin:0 auto;box-sizing:border-box;border:1px solid #e1e5e8;overflow-wrap:anywhere;text-align:left;color-scheme:light}
.customer-document *{box-sizing:border-box}.customer-document p{margin:6px 0;white-space:pre-wrap}.customer-document h1,.customer-document h2,.customer-document h3{color:#14181c;line-height:1.2;margin:0;letter-spacing:0}
.customer-document.receipt{padding:0;border-radius:0}.customer-document small{color:inherit}.customer-document .doc-footer{margin:0;color:var(--doc-on-primary);font-size:11px}
.doc-header{overflow:hidden}
.customer-document h1{font-size:22px;font-weight:800}.customer-document h2{font-size:15px;font-weight:800;display:flex;align-items:center;gap:8px;margin-bottom:9px}.customer-document h3{font-size:12px;text-transform:uppercase;margin-bottom:6px}
.doc-header{display:grid;grid-template-columns:1.2fr 1fr;gap:20px;padding:20px 24px;min-height:125px;background:var(--doc-primary);color:var(--doc-on-primary);position:relative;border-bottom:6px solid var(--doc-accent);isolation:isolate}
.doc-header:after{content:'';position:absolute;right:26px;top:0;height:100%;width:15px;transform:skew(-30deg);background:var(--doc-accent);opacity:.4;z-index:-1}
.doc-header:has(.doc-invoice-title){grid-template-columns:1.1fr 1fr .9fr;gap:15px}.doc-brand{align-self:center;min-width:0}.doc-brand img{max-height:82px;max-width:100%;width:auto;object-fit:contain;display:block;margin-bottom:5px}.doc-brand strong{font-size:23px;line-height:1.1;display:block}.doc-brand:has(img) strong{font-size:14px}
.doc-contact{font-size:11px;display:grid;gap:6px;align-content:center;padding-right:15px}.doc-invoice-title{background:white;color:#171c21;padding:12px;align-self:center;text-align:center}.doc-invoice-title h1{font-size:29px}.doc-invoice-title div{font-size:11px;margin-top:4px}
.doc-status{display:block;font-weight:bold;padding:5px 8px;margin-top:6px}.paid{background:#e8f3e9!important;color:#20552f!important}.pending{background:#fff0da;color:#6e3c05}
.doc-body{padding:18px 22px}.doc-intro{display:grid;grid-template-columns:1.4fr 1fr;gap:16px;margin-bottom:18px}.doc-intro>div:first-child{border-left:4px solid var(--doc-accent);padding-left:10px}.doc-intro h1{font-size:18px}.doc-intro p{font-size:11px}.doc-intro>div:last-child{padding-left:12px;border-left:1px solid #ddd}
.doc-identities{display:grid;grid-template-columns:1fr 1.4fr;gap:12px;margin-bottom:12px}.doc-section{margin:0 0 13px;padding-top:9px;border-top:1px solid var(--doc-accent);break-inside:avoid}.doc-identities .doc-section{border:1px solid var(--doc-accent);padding:12px;margin:0}.doc-dot{background:var(--doc-accent);color:var(--doc-on-accent);border-radius:50%;width:25px;height:25px;display:inline-grid;place-items:center;font-size:13px;flex-shrink:0}
.doc-row{display:flex;justify-content:space-between;gap:10px;padding:5px 8px;border-bottom:1px solid #edf0f2;font-size:12px}.doc-row strong{text-align:right;font-weight:600}.doc-identities .doc-row{padding:2px 0;border:0}.doc-identities .doc-row strong{text-align:left;flex:1}.doc-identities .doc-row span{width:68px;flex-shrink:0}
.doc-work-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.doc-work{background:#f3f4f5;padding:11px;break-inside:avoid}.doc-work ul{padding-left:15px;margin:0}.customer-document .doc-work li{margin:3px 0;font-size:12px;line-height:1.35}
.doc-pair{display:grid;grid-template-columns:1fr 1fr;gap:14px}.doc-pair .doc-section{padding:9px 8px;border:1px solid #e1e5e8;border-top-color:var(--doc-accent)}.doc-pair p{font-size:12px}.doc-pair .doc-row{padding:3px 0;font-size:11px}
.doc-economic{display:grid;grid-template-columns:1.6fr 1fr;gap:14px}.doc-economic .doc-row{padding:7px 8px}.doc-highlight{background:var(--doc-accent);color:var(--doc-on-accent);font-weight:700}.doc-payment-callout{padding:12px;background:#f3f4f5;display:flex;flex-direction:column;justify-content:center;gap:4px}.doc-payment-callout strong{font-size:22px;line-height:1.2}.doc-payment-callout small{font-size:11px;margin-bottom:6px}.doc-payment-callout b{font-size:13px}
.customer-document table{border-collapse:collapse;width:100%;font-size:12px;table-layout:fixed}.customer-document th,.customer-document td{padding:5px 8px;border-bottom:1px solid #e4e7eb;text-align:left;color:#20252b;white-space:normal}.customer-document th{background:#f1f3f5}.customer-document th:last-child,.customer-document td:last-child{text-align:right}.customer-document thead{display:table-header-group}.customer-document tr{break-inside:avoid}
.doc-signatures{display:grid;grid-template-columns:1fr 1fr;gap:30px;align-items:end;margin:24px 6px 8px;break-inside:avoid}.doc-signature-line{border-bottom:1px solid #7b8288;height:25px;margin-bottom:5px}.doc-signatures span,.doc-signatures p{font-size:10px}
.doc-footer{display:flex;justify-content:space-between;gap:20px;padding:12px 22px;background:var(--doc-primary);color:var(--doc-on-primary);font-size:11px;border-top:5px solid var(--doc-accent);break-inside:avoid}.doc-footer em{font-size:15px}
dialog.document-dialog{max-width:890px;width:calc(100% - 24px);padding:18px;background:#eef1f4;color:#17212b}dialog.document-dialog .dialog-top{background:#eef1f4;color:#17212b}dialog.document-dialog .dialog-top h2{color:#17212b}dialog.document-dialog .doc-controls{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}dialog.document-dialog .btn{background:#fff;color:#17212b;border:1px solid #b7c1cc}
.document-standalone{background:#edf0f3;margin:0;padding:24px 0}.document-standalone .customer-document{box-shadow:0 8px 30px #1324351a}
@media screen and (max-width:600px){.doc-header,.doc-header:has(.doc-invoice-title){grid-template-columns:1fr;padding:18px;gap:12px}.doc-header{min-height:0}.doc-brand img{max-height:75px}.doc-contact{padding:0}.doc-invoice-title{text-align:left}.doc-body{padding:14px}.doc-intro,.doc-identities,.doc-pair,.doc-economic{grid-template-columns:1fr}.doc-intro>div:last-child{border:0;padding:0}.doc-work-grid{grid-template-columns:1fr}.doc-work ul{columns:1}.doc-signatures{grid-template-columns:1fr;gap:10px}.doc-footer{flex-wrap:wrap;padding:12px 14px}.doc-intro h1{font-size:20px}.customer-document{font-size:14px}.document-standalone{padding:0}dialog.document-dialog{padding:10px;width:calc(100% - 12px)}.doc-controls .btn{flex:1 1 130px}}
@page{size:letter;margin:10mm}
@media print{.doc-header{min-height:100px;padding:12px 16px;gap:12px}.doc-brand img{max-height:60px}.doc-invoice-title{padding:7px}.doc-invoice-title h1{font-size:25px}.doc-intro{margin-bottom:12px}.doc-identities .doc-section{padding:8px}.doc-identities .doc-row{padding:1px 0}.customer-document h2{font-size:14px;margin-bottom:6px}.doc-dot{width:22px;height:22px}.doc-section{margin-bottom:9px;padding-top:6px}.doc-work{padding:8px}.doc-work-grid:has(>.doc-work:nth-child(4)):not(:has(>.doc-work:nth-child(5))){grid-template-columns:repeat(4,minmax(0,1fr))}.customer-document .doc-work li{font-size:11px;margin:2px 0}.customer-document .doc-work h3{font-size:11px}.doc-economic .doc-row{padding:4px 6px}.doc-pair .doc-section{padding:7px}.doc-pair p{font-size:11px}.doc-pair .doc-row{font-size:10px}.doc-signatures{margin-top:12px}.doc-signature-line{height:18px}.customer-document .doc-footer{padding:9px 16px}.customer-document th,.customer-document td{padding:4px 6px;font-size:11px}}
@media print{html,body.document-standalone{background:#fff;margin:0;padding:0}.customer-document{max-width:none;width:100%;border:0;font-size:12px;box-shadow:none!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.doc-header{break-inside:avoid}.doc-body{padding:14px 16px}.doc-section:has(table){break-inside:auto}.doc-section:has(.doc-work-grid){break-inside:auto}.doc-work-grid{align-items:start}.doc-header,.doc-footer{print-color-adjust:exact}.doc-controls,.dialog-top{display:none!important}body:has(dialog.document-dialog[open])>#app,body:has(dialog.document-dialog[open])>#toast{display:none!important}dialog.document-dialog[open]{display:block;position:static;margin:0;padding:0;width:100%;max-width:none;max-height:none;overflow:visible;border:0;background:white}dialog.document-dialog::backdrop{background:none}}
@media print{.doc-header{padding:9px 16px;min-height:90px}.doc-header .doc-invoice-title{padding:5px;font-size:11px}.doc-header .doc-invoice-title h1{font-size:23px}.doc-header .doc-invoice-title .doc-status{padding:3px 6px;margin-top:4px}.doc-body{padding:10px 16px}.doc-identities .doc-row{font-size:11px}.doc-economic .doc-row{font-size:11px;padding:3px 6px}.doc-section{margin-bottom:7px;padding-top:5px}.customer-document h2{margin-bottom:5px}.doc-dot{width:20px;height:20px}.doc-signatures{margin-top:8px}}
`;
