import assert from 'node:assert/strict';
import {writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {start,out} from './harness.mjs';
const h=await start(),{page:p,origin}=h,checks=[],consoleErrors=[];
p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
const button=n=>p.getByRole('button',{name:n,exact:true}),field=n=>p.getByLabel(n,{exact:true});
const go=async r=>{await p.goto(origin+'/index.html#'+r);await p.locator('.top').waitFor();};
const saved=async n=>{await button(n).click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);};
const data=()=>p.evaluate(async()=>new (await import('./service.mjs')).TallerService().state());
const check=s=>{checks.push(s);console.log('PASS '+s);};
try{
 await go('clients');await p.clock.setFixedTime(new Date('2026-09-08T12:00:00-04:00'));
 await button('Nuevo cliente').click();await field('Nombre completo').fill('Carla Auditoría');await field('Teléfono').fill('8095550123');await saved('Guardar cliente');await p.waitForURL('**#client/*');
 await button('Editar cliente').click();await field('WhatsApp').fill('8295550987');await field('Nombre completo').fill('Carla Auditoría Final');await saved('Guardar cliente');await p.getByRole('heading',{name:'Carla Auditoría Final',exact:true}).waitFor();
 await button('Agregar vehículo').click();await field('Marca').fill('Toyota');await field('Modelo').fill('Corolla');await field('Año').fill('2014');await field('Placa').fill('TEST-0241');await saved('Guardar vehículo');
 await p.locator('section').filter({has:p.getByRole('heading',{name:'Vehículos',exact:true})}).getByRole('button',{name:'Editar',exact:true}).click();await field('Color').fill('Gris');await saved('Guardar vehículo');
 let d=await data();assert.equal(d.clients[0].whatsapp,'8295550987');assert.equal(d.vehicles[0].color,'Gris');check('Crear, editar y consultar cliente y vehículo relacionados');
 for(const [name,role,rate] of [['Empleado A','Desabollador',500],['Empleado B','Preparador',300],['Empleado C','Pintor',400]]){await go('employees');await button('Agregar empleado').click();await field('Nombre').fill(name);await field('Puesto').fill(role);await field('Tarifa por pieza').fill(String(rate));await saved('Guardar empleado');}
 await go('orders');await button('Nueva orden').click();await field('Vehículo').selectOption({label:'Toyota · Corolla · TEST-0241'});await field('Precio acordado').fill('60000');await field('Fecha de entrada').fill('2026-09-01');await field('Entrega prevista').fill('2026-09-08');await field('Abono inicial').fill('20000');await field('Fecha del abono').fill('2026-09-01');await field('Condiciones del trabajo').fill('Solo piezas indicadas; cambios con autorización.');await field('Observaciones de recepción').fill('Rayón previo en bumper trasero.');
 const selections=[['Bumper delantero',['Preparación','Pintura']],['Puerta delantera derecha',['Desabolladura','Preparación','Pintura']],['Capó',['Pintura']]];
 for(let i=0;i<selections.length;i++){if(i)await button('+ Agregar pieza').click();const row=p.locator('.reception-piece').nth(i);await row.getByLabel('Pieza',{exact:true}).fill(selections[i][0]);for(const process of selections[i][1])await row.getByLabel(process,{exact:true}).check();}
 await button('Guardar orden').click();await p.locator('.customer-document').waitFor();assert.match(await p.locator('.customer-document').innerText(),/40,000.00/);await button('Cerrar').click();await p.waitForURL('**#order/*');const route=p.url().split('#')[1];
 d=await data();const order=d.orders[0];assert.equal(d.payments.length,1);assert.equal(d.workAssignments.length,3);assert.equal(d.vehiclePieces.length,3);
 await button('•••').click();await button('Editar orden').click();await field('Entrega prevista').fill('2026-09-09');await saved('Guardar orden');assert.equal((await data()).orders[0].dueDate,'2026-09-09');
 await button('Registrar abono').click();await field('Monto recibido').fill('50000');await button('Guardar pago').click();await p.locator('.form-error').getByText('El pago supera el saldo pendiente.',{exact:true}).waitFor();assert.equal((await data()).payments.length,1);await button('Cancelar').click();check('Orden, comprobante, abono único, entrega editable y rechazo de sobrepago sin escritura');
 for(const [process,employee] of [['Desabolladura','Empleado A'],['Preparación','Empleado B'],['Pintura','Empleado C']]){
  const card=p.locator('.work-card').filter({has:p.getByRole('heading',{name:process,exact:true})});await card.getByRole('button',{name:'Asignar empleado',exact:true}).click();await field('Empleado').selectOption({label:employee});await saved('Guardar asignación');
  await card.getByRole('button',{name:'Opciones de '+process}).click();await button('Iniciar trabajo').click();await card.locator('.badge').filter({hasText:'En proceso'}).waitFor();
  await card.getByRole('button',{name:'Terminar',exact:true}).click();await saved('Terminar trabajo');await card.locator('.badge').filter({hasText:'Terminado'}).waitFor();
 }
 d=await data();assert.deepEqual(d.ledgerAccruals.map(x=>x.total).sort((a,b)=>a-b),[500,600,1200]);check('Tres empleados, producción independiente y mano de obra 500 + 600 + 1,200 = 2,300');
 await button('Rentabilidad').click();for(const [type,description,amount] of [['Materiales','Pintura y consumibles',12000],['Otros costos','Transporte autorizado',700]]){await button('Agregar costo').click();await field('Tipo').selectOption(type);await field('Concepto').fill(description);await field('Monto total').fill(String(amount));await field('Fecha del costo').fill('2026-09-08');await saved('Guardar costo');}
 await button('Cobrar saldo').click();await field('Monto recibido').fill('10000');await field('Fecha').fill('2026-09-05');await saved('Guardar pago');await p.locator('.status-panel').getByText(/30,000/).waitFor();
 await button('Cobrar saldo').click();await field('Monto recibido').fill('30000');await field('Método de pago').selectOption('Transferencia');await field('Fecha').fill('2026-09-08');await saved('Guardar pago');await button('Finalizar y entregar').waitFor();
 await button('Finalizar y entregar').click();await button('Cancelar').click();assert.notEqual((await data()).orders[0].lifecycle,'closed');
 await button('Finalizar y entregar').click();await field('Tiene garantía').selectOption('yes');await field('Duración de garantía').fill('6 meses');await field('Inicio de garantía').fill('2026-09-08');await field('Vencimiento de garantía').fill('2027-03-08');await field('Condiciones de garantía').fill('Defectos de adherencia en uso normal.');await button('Finalizar orden').click();await p.locator('.customer-document').waitFor();assert.match(await p.locator('.customer-document').innerText(),/PAGADO/);assert.equal(await p.locator('.customer-document tbody tr').count(),3);assert.doesNotMatch(await p.locator('.customer-document').innerText(),/Empleado A|Empleado B|Empleado C|12,000|2,300|45,000/);await button('Cerrar').click();
 const f=await p.evaluate(async()=>{const s=new (await import('./service.mjs')).TallerService(),d=await s.state();return (await import('./domain.mjs')).financial(d,d.orders[0]);});assert.equal(f.revenue,60000);assert.equal(f.collected,60000);assert.equal(f.balance,0);assert.equal(f.costs,15000);assert.equal(f.profit,45000);assert.equal(f.margin,75);check('Cierre confirmado, factura final, total cobrado 60,000, costos 15,000 y utilidad 45,000 / 75%');
 for(const r of ['home','orders','production']){await go(r);assert.equal(await p.locator('main').getByText(order.number,{exact:true}).count(),0);}await go('history');await p.getByRole('link',{name:/TEST-0241/}).click();await button('Rentabilidad').click();assert.match(await p.locator('main').innerText(),/45,000/);check('Orden cerrada conservada en historial y excluida de operación');
 await go('employees');await p.getByRole('link',{name:/Empleado A/}).click();await button('Registrar pago').click();await field('Monto').fill('200');await field('Fecha').fill('2026-09-08');await saved('Guardar pago');await p.getByRole('heading',{name:'Historial de pagos'}).waitFor();
 let summary=await p.evaluate(async()=>{const d=await new (await import('./service.mjs')).TallerService().state(),m=await import('./domain.mjs');return {employee:m.employeeSummary(d,d.employees[0].id),finance:m.financial(d,d.orders[0])};});assert.equal(summary.employee.balance,300);assert.equal(summary.finance.profit,45000);check('Historial del empleado: pago 200, saldo 300; pagar no duplica el costo');
 await go('inventory');await button('Nuevo producto').click();await field('Producto').fill('Clear auditoría');await field('Cantidad inicial').fill('10');await field('Costo unitario').fill('100');await field('Stock mínimo').fill('3');await saved('Guardar producto');await p.waitForURL('**#product/*');await button('Salida').click();await field('Cantidad').fill('11');await button('Guardar movimiento').click();await p.locator('.form-error').getByText('No hay suficiente inventario.',{exact:true}).waitFor();await button('Cancelar').click();
 await button('Entrada').click();await field('Cantidad').fill('5');await field('Costo unitario de compra').fill('120');await saved('Guardar movimiento');await button('Salida').click();await field('Cantidad').fill('4');await saved('Guardar movimiento');d=await data();assert.equal(d.inventory[0].quantity,11);assert.equal(d.inventory[0].unitCost,106.67);check('Inventario y promedio ponderado; salida excesiva rechazada');
 await p.clock.setFixedTime(new Date('2026-10-02T12:00:00-04:00'));await go('monthly');await field('Período').fill('2026-09');await field('Período').dispatchEvent('change');await button('Cerrar mes y guardar instantánea').click();await button('Cancelar').click();assert.equal((await data()).monthlyClosures.length,0);await button('Cerrar mes y guardar instantánea').click();await saved('Guardar cierre');d=await data();assert.equal(d.monthlyClosures[0].metrics.cash,60000);assert.equal(d.monthlyClosures[0].metrics.profit,45000);check('Cierre mensual confirmado: caja 60,000 y utilidad 45,000');
 await go('settings');const dl=p.waitForEvent('download');await button('Exportar todos los datos').click();const download=await dl;const exported=JSON.parse(await readFile(await download.path(),'utf8'));assert.equal(exported.main.orders.length,1);assert.equal(exported.main.payments.length,3);assert.equal(exported.phase2.invoices.length,1);assert.equal(exported.main.orders[0].initialReceipt.paid,20000);check('Respaldo exportado contiene órdenes, ambos documentos, pagos y garantía');
 // Import only this generated backup into the isolated test context.
 await button('Importar copia').click();await p.locator('#backup-file').setInputFiles({name:'auditoria.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await button('Cancelar').click();assert.equal((await data()).orders.length,1);
 await button('Importar copia').click();await p.locator('#backup-file').setInputFiles({name:'auditoria.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await saved('Importar y reemplazar');await p.reload();await p.locator('.top').waitFor();d=await data();assert.equal(d.payments.length,3);assert.equal(d.invoices[0].warranty.endDate,'2027-03-08');check('Importación confirmada, recuperación previa y persistencia tras recargar');
 // Inspect real text wrapping and form usability with reduced height (keyboard space).
 await go('clients');await p.getByRole('link',{name:/Carla Auditoría/}).click();await button('Editar cliente').click();await field('Nombre completo').fill('Carla '+ 'ApellidoLargo'.repeat(15));await saved('Guardar cliente');
 const sizing=[];
 for(const width of [320,375,390,430,1280]){await p.setViewportSize({width,height:844});for(const r of ['home','orders','production','clients','client/1','history',route,'employees','employee/1','inventory','monthly','settings','more']){await go(r);const size=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));sizing.push({r,width,...size});assert.ok(size.scroll<=width+1,'Desborde '+r+' '+width+': '+size.scroll);}}
 await p.setViewportSize({width:390,height:360});await go('orders');await button('Nueva orden').click();await field('Condiciones del trabajo').fill('Texto largo '.repeat(100));await button('Guardar orden').scrollIntoViewIfNeeded();const rect=await button('Guardar orden').boundingBox();assert.ok(rect.y>=0&&rect.y+rect.height<=360);await p.screenshot({path:path.join(out,'audit-keyboard.png')});await button('Cancelar').click();check('13 vistas con nombres largos a 320/375/390/430/1280 y modal con espacio de teclado');
 assert.deepEqual(h.errors,[]);assert.deepEqual(consoleErrors,[]);await writeFile(path.join(out,'final-audit-results.json'),JSON.stringify({status:'passed',checks,finance:f,sizing},null,2));
}catch(e){await p.screenshot({path:path.join(out,'final-audit-failure.png'),fullPage:true}).catch(()=>{});console.error('BROWSER ERRORS',h.errors,consoleErrors);throw e;}finally{await h.stop();}
